### PR TITLE
WIP: Added extra property to build for not running any test at all during packaging

### PR DESCRIPTION
**Pull request by QLaille**
The extra line in the pom asks maven to skip all tests during packaging.
To merge only if #202 is resolved, as we can also skip tests during package with an extra flag for maven.

### CODE REVIEW

**Comment by fluffy-hamster** [comment]
quick question:  Why would we want to skip tests?

**Comment by QLaille** [comment]
TBF I don't know, I just prepared the PR in case we came to the same conclusion in the related issue.

**Comment by fluffy-hamster** [comment]
Imo, the entire point of unit tests is that you run them ALL the time. 

If tests are broken, we shouldn't be submitting the code full stop.  (always fix the tests first). 

So, unless you can give a compelling reason for doing this, as far as I am concerned skipping tests is exactly the sort of thing we SHOULD NOT be doing

**Comment by fluffy-hamster** [comment]
closing issue because it was decided we want unit tests to run all the time

**Pull request closed without merging**
