### PR TITLE
Increase maximum amount of cards the player can hold in their hand to 6

### PR DESCRIPTION
**Pull request by Ridleh**
Also removes the player's hand that hold's items, which renders the items you pick up on the board useless.

### CODE REVIEW

**Comment by themetalfleece** [comment]
I would suggest having the maximum number of cards to a variable (maybe to config file) so it can easily change and it also reduces the chances of errors (since it's referenced in 2 places)

**Comment by Ridleh** [comment]
> 
> 
> I would suggest having the maximum number of cards to a variable (maybe to config file) so it can easily change and it also reduces the chances of errors (since it's referenced in 2 places)

We dont have a config file but we have a file holding a bunch of constants. Could creating a new constant CARD_HAND_SIZE = 6 work?

**Comment by themetalfleece** [comment]
@Ridleh yes that would do for now, and if we create a config file in the future we can easily move it there without searching anything in the code.
Feel free to push the change in this branch and the PR will be automatically updated

**Comment by alex-gonz** [comment]
Could you also update this check from from CompressedPlayer.java?
```
        if (hand.size() > 5)
            System.out.println("Client Game Error!");
```

Doesn't stop anything from working, but it'll be weird seeing those log messages + tracking them down.

**Comment by Ridleh** [comment]
> 
> 
> Could you also update this check from from CompressedPlayer.java?
> 
> ```
>         if (hand.size() > 5)
>             System.out.println("Client Game Error!");
> ```
> 
> Doesn't stop anything from working, but it'll be weird seeing those log messages + tracking them down.

Will do

**Comment by Ridleh** [comment]
Changes have been made based on feedback.

**Comment by Ridleh** [comment]
@fluffy-hamster John Doe.json is irrelevant, but the .gitignore hasnt been update to ignore it.

**Pull request merged**
