### PR TITLE
Add logging

### PR DESCRIPTION
**Pull request by fluffy-hamster**
todo: 

- test on server
- test on exe

### CODE REVIEW

**Comment by skeet70** [comment]
I started looking at this and I'll try to finish checking it out in the future, but did you look at SLF4J or any of the other existing abstractions before writing your own around `println`? [This](https://www.vogella.com/tutorials/Logging/article.html) shows an example of using Java's util logger, and [this](https://stackify.com/slf4j-java/) gives some examples using slf4j and shows how easy it is to swap out targets. That'll help going forward if we want to change where we're outputting logs easily without hardcoding file locations (like sending to a central logging framework, a metrics system, a file, stdout, whatever else we want to) or swapping out the logging implementation entirely without changing the code.

**Comment by fluffy-hamster** [comment]
@skeet70 
So the key file here is the "log" class in shared, which is basically a wrapper around Java.utils.log. 

I tried to keep things somewhat flexible by creating a 'client log message' and a 'server log message'. So with a bit of extra work it would be possible to hook this up to different log files.

**Comment by skeet70** [comment]
It's sort of a wrapper around `java.util.log` but it's also a wrapper around `println` (https://github.com/Duelers/Duelers/pull/461/files#diff-02546cd9ad443b9c7a5863c4f0ad6986R105-R112). I'm not sure if that really answers my question though of why use a custom solution like this instead of a standard logging abstraction?

**Comment by fluffy-hamster** [comment]
> It's sort of a wrapper around `java.util.log` but it's also a wrapper around `println` (https://github.com/Duelers/Duelers/pull/461/files#diff-02546cd9ad443b9c7a5863c4f0ad6986R105-R112). I'm not sure if that really answers my question though of why use a custom solution like this instead of a standard logging abstraction?

If I'm not answering your question it is probably because I'm not fully understanding the question. :)

As a general rule, I'm not a fan of creating "custom solutions" when code already exists. I did a bit of research and this is the best I could up with within the allotted time.

Anyway, I built a wrapper with the methods ClientLog/ServerLog because I thought in the future we may wish to have separate log files. I figured this was easier to do with a wrapper, as opposed to having the logger calls directly in the code. In the latter case we'd probably need several logger objects (one for client, server, etc) or something. 

If there is a better way to do things then I'm more than happy to start from scratch on this. But yeah, the code is the way it is because this was the first way I found todo all the things I thought I wanted.

**Comment by skeet70** [comment]
I gave two links to examples that are both better existing options, as well as the info that was in #357 about SLF4J. Just to regurgitate the links and provide additional context:

* https://www.vogella.com/tutorials/Logging/article.html shows using `Java.util.log` without any abstraction in the right way. For ex you'd use https://docs.oracle.com/javase/7/docs/api/java/util/logging/ConsoleHandler.html to go to the console instead of `println`, probably change all the `logX` to a single `log` function that takes an enum for the prefix, use `java.lang.Throwable` instead of overriding the same behaviour on `Exception` and `Error`

* https://stackify.com/slf4j-java/ shows using the more standard SLF4J abstraction, which we could just back with log4j2 or logback (doesn't matter which we choose because we can switch it later without changing _any_ code if requirements change, but log4j2 is supposed to be an improved version of logback). Benefit to this is that it's completely logging framework agnostic, whatever changes we need to make in the future require no/minimal code changes. This is the one I'd prefer. https://www.logicbig.com/tutorials/misc/java-logging/slf4j-with-log4j2.html and https://medium.com/@krishankantsinghal/logback-slf4j-log4j2-understanding-them-and-learn-how-to-use-d33deedd0c46 give really basic examples of setting this up.

Hopefully that helps

**Pull request closed without merging**
